"""Add phone field to students table

Revision ID: 5344d4b292dc
Revises: 18e1c28ab72f
Create Date: 2026-03-07 11:57:49.376285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5344d4b292dc'
down_revision: Union[str, Sequence[str], None] = '18e1c28ab72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('phone', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('students_contact_phone_key'), 'students', type_='unique')
    op.create_unique_constraint(None, 'students', ['phone'])
    op.drop_column('students', 'contact_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'students', type_='unique')
    op.create_unique_constraint(op.f('students_contact_phone_key'), 'students', ['contact_phone'], postgresql_nulls_not_distinct=False)
    op.drop_column('students', 'phone')
    # ### end Alembic commands ###
