"""Initial migration

Revision ID: d096d5629ff1
Revises: 
Create Date: 2026-03-06 16:14:38.184171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd096d5629ff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('remaining_classes', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('remaining_fee', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('enrollment_date', sa.Date(), nullable=True))
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('students', 'grade',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('students', 'project',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.create_unique_constraint(None, 'students', ['phone'])
    op.add_column('teachers', sa.Column('name', sa.String(length=50), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('teachers', 'name')
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('students', 'project',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'grade',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'gender',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('students', 'enrollment_date')
    op.drop_column('students', 'remaining_fee')
    op.drop_column('students', 'remaining_classes')
    # ### end Alembic commands ###
