"""Remove admin, age, gender, grade, subject fields from User model

Revision ID: d293baca5c98
Revises: d096d5629ff1
Create Date: 2026-03-07 10:43:16.362457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd293baca5c98'
down_revision: Union[str, Sequence[str], None] = 'd096d5629ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('users', 'age')
    op.drop_column('users', 'subject')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'grade')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('grade', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
